# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-07-19 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200719_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default=4, max_length=40),
            preserve_default=False,
        ),
    ]
