# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-17 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description_section', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(default='€', max_length=1)),
                ('images', models.ImageField(blank=True, upload_to='images')),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
